export enum Diseas {
  CELIAC = 'CELIAC',

  GLUTEN_SENSITIVE = 'GLUTEN_SENSITIVE',

  GLUTEN_INTOLERENCE = 'GLUTEN_INTOLERENCE',

  CHRON_DISEAS = 'CHRON_DISEAS',

  IBS = 'IBS',

  OTHER = 'OTHER',
}
